[project]
name = "spark-scraper"
version = "0.1.0"
description = "监控 Spark 新代币创建的爬虫程序"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "playwright>=1.40.0",
    "requests>=2.31.0",
    "python-dotenv>=1.0.0",
]
